version: '3.6'
services:
  
  iris:
    build: 
      context: iris-db
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972:1972
      - 52773:52773
      - 53773:53773
    volumes:
      - ./:/irisrun/repo
  
  appserver:
    build:
       context: springboot-app
       dockerfile: Dockerfile
    image: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - iris 
